/**
 * Artifact Manager
 * Manages artifact data, rendering, and interactions
 */

// Artifact Store
const ArtifactStore = {
  artifacts: new Map(),
  currentArtifact: null,

  add(artifact) {
    this.artifacts.set(artifact.id, artifact);
    this.updateArtifactCount();
  },

  get(id) {
    return this.artifacts.get(id);
  },

  getAll() {
    return Array.from(this.artifacts.values());
  },

  setCurrent(id) {
    this.currentArtifact = this.get(id);
  },

  getCurrent() {
    return this.currentArtifact;
  },

  updateArtifactCount() {
    const count = this.artifacts.size;
    const countEl = document.querySelector('.artifact-count');
    if (countEl) {
      countEl.textContent = `Artifacts (${count})`;
    }
  }
};

// Utility Functions
function escapeHTML(str) {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}

function formatTimestamp(isoString) {
  const date = new Date(isoString);
  return date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
}

// Initialize sample artifacts
function initializeSampleArtifacts() {
  // Sample Document Artifact
  ArtifactStore.add({
    id: 'artifact-001',
    type: 'document',
    title: 'Financial Analysis Report Q3 2024',
    content: `# Analisis Keuangan Q3 2024

## Ringkasan Eksekutif

Laporan ini menyajikan analisis mendalam terhadap performa keuangan Q3 2024, mencakup tren pendapatan, margin profitabilitas, dan rekomendasi strategis untuk Q4 2024.

## Temuan Utama

### 1. Pertumbuhan Pendapatan
- Q3 2024: **Rp 45.8 Miliar** (+12.3% QoQ)
- Year-over-year growth: **18.5%**
- Momentum positif dengan akselerasi dari 8.2% (Q1) ke 12.3% (Q3)

### 2. Segmentasi Pendapatan
- **Sektor A:** 58% kontribusi (Rp 26.6M) - growth 10.2%
- **Sektor B:** 28% kontribusi (Rp 12.8M) - growth 22.7% ⭐
- **Sektor C:** 14% kontribusi (Rp 6.4M) - growth 7.8%

### 3. Profitabilitas
- Gross margin: **44.1%** (↑ dari 42.3%)
- Operating margin: **18.5%** (tertinggi dalam 2 tahun)
- Net profit margin: **12.8%** (+1.4 poin)

## Rekomendasi Strategis

### Prioritas Tinggi
1. **Fokus pada Sektor B** - momentum kuat dengan growth 22.7%
2. **Efisiensi Operasional** - target saving 3-4% dari operating expenses
3. **Cash Collection** - turunkan DSO dari 52 hari ke 40-42 hari

### Prioritas Medium
1. **Revitalisasi Sektor C** - product refresh untuk meningkatkan growth
2. **Diversifikasi Revenue** - kurangi dependency Sektor A dari 58% ke 45-50%
3. **Automation Investment** - reduce operating costs jangka panjang

## Target Q4 2024
- Revenue: **Rp 50-52 Miliar** (growth 9-14%)
- Operating margin: **18-19%**
- Net profit margin: **13.5-14%**

---

*Generated by Public Data Insight Agent*`,
    timestamp: '2025-10-24T13:16:00Z',
    messageId: 'msg-003',
    metadata: {
      wordCount: 1240
    }
  });
}

// Export for use in app.js
window.ArtifactStore = ArtifactStore;
window.initializeSampleArtifacts = initializeSampleArtifacts;
window.escapeHTML = escapeHTML;
window.formatTimestamp = formatTimestamp;
